name: 'Gatsby pages build'
description: 'An action that builds your Gatsby site for GitHub Pages using npm'
inputs:
  node-version:
    description: 'The version of node'
    required: true
    default: '16'
    
runs:
  using: "composite"
  steps:     
    - name: Check package manager
      id: check-package-manager
      run: |
        [ -f "${{ github.workspace }}/yarn.lock" ] && YARN=true || YARN=false
        [ -f "${{ github.workspace }}/package-lock.json" ] && NPM=true || NPM=false
        
        if [[ "$YARN"=="true"]]; then
          echo "::set-output name=manager::yarn"
          echo "::set-output name=command::install"
          exit 0
        fi
        
        if [[ "$NPM"=="true" ]]; then
          echo "::set-output name=manager::npm"
          echo "::set-output name=command::ci"
          exit 0
        fi
        
      shell: bash
        
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ steps.check-package-manager.outputs.manager }}
        
    - name: cache gatsby site build
      id: gatsby-cache-build
      uses: actions/cache@v2
      with:
        path: |
          public
          .cache
        key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
        restore-keys: |
          ${{ runner.os }}-gatsby-build-

    - run: ${{ steps.check-package-manager.outputs.manager }} ${{ steps.check-package-manager.outputs.command }}
      shell: bash
      
    - run: ${{ steps.check-package-manager.outputs.manager }} run build --if-present
      shell: bash
